# Introduction to Python for Machine Learning
## Quiz tag-along code

In [1]:
import pandas as pd
import numpy as np

In [2]:
array = np.array ([[94, 89, 63], [93, 92, 48], [92, 94, 56]])
print(array)

[[94 89 63]
 [93 92 48]
 [92 94 56]]


In [3]:
array[:2,1:]

array([[89, 63],
       [92, 48]])

In [4]:
food = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding = 'latin-1')
food.head()

Area Code     Area  Item Code         Item  Element Code  \
0          4  Algeria       2501   Population           511   
1          4  Algeria       2501   Population          5301   
2          4  Algeria       2901  Grand Total           664   
3          4  Algeria       2901  Grand Total           674   
4          4  Algeria       2901  Grand Total           684   

                                  Element             Unit     Y2014  \
0           Total Population - Both sexes     1000 persons  38924.00   
1                Domestic supply quantity      1000 tonnes      0.00   
2           Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3  Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4      Fat supply quantity (g/capita/day)     g/capita/day     80.06   

      Y2015     Y2016     Y2017     Y2018  
0  39728.00  40551.00  41389.00  42228.00  
1      0.00      0.00      0.00      0.00  
2   3379.00   3372.00   3341.00   3322.00  
3     94.35     94.72     92.82     91.83  
4     79.36     77.40     80.19     77.28

In [5]:
food.groupby('Item')['Y2015', 'Y2018'].sum()

C:\Users\QUEEN\AppData\Local\Temp\ipykernel_14136\3318117269.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  food.groupby('Item')['Y2015', 'Y2018'].sum()


Y2015      Y2018
Item                                     
Alcohol, Non-Food      2180.00    2293.00
Alcoholic Beverages   98783.72   97847.27
Animal Products       11811.73   11578.61
Animal fats          200675.72  269648.27
Apples and products   10559.15    9640.51
...                        ...        ...
Vegetables, Other    158104.08  163987.21
Vegetal Products     107064.17  107775.39
Wheat and products   234710.51  242645.19
Wine                   4251.81    4039.32
Yams                 203151.78  221272.09

[119 rows x 2 columns]

In [6]:
# Had the wine sum not been visible,the loc function can be used to locate it
Item = food.groupby('Item')['Y2015', 'Y2018'].sum()
Item.loc['Wine']

C:\Users\QUEEN\AppData\Local\Temp\ipykernel_14136\3913759304.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Item = food.groupby('Item')['Y2015', 'Y2018'].sum()


Y2015    4251.81
Y2018    4039.32
Name: Wine, dtype: float64

In [7]:
# To filter for Madagascar
food[food['Area']== 'Madagascar']

Area Code        Area  Item Code           Item  Element Code  \
30715        129  Madagascar       2501     Population           511   
30716        129  Madagascar       2501     Population          5301   
30717        129  Madagascar       2901    Grand Total           664   
30718        129  Madagascar       2901    Grand Total           674   
30719        129  Madagascar       2901    Grand Total           684   
...          ...         ...        ...            ...           ...   
32149        129  Madagascar       2899  Miscellaneous          5142   
32150        129  Madagascar       2899  Miscellaneous           645   
32151        129  Madagascar       2899  Miscellaneous           664   
32152        129  Madagascar       2899  Miscellaneous           674   
32153        129  Madagascar       2899  Miscellaneous           684   

                                      Element             Unit     Y2014  \
30715           Total Population - Both sexes     1000 persons  23590.00   
30716                Domestic supply quantity      1000 tonnes      0.00   
30717           Food supply (kcal/capita/day)  kcal/capita/day   1986.00   
30718  Protein supply quantity (g/capita/day)     g/capita/day     44.45   
30719      Fat supply quantity (g/capita/day)     g/capita/day     22.18   
...                                       ...              ...       ...   
32149                                    Food      1000 tonnes     10.00   
32150     Food supply quantity (kg/capita/yr)               kg      0.44   
32151           Food supply (kcal/capita/day)  kcal/capita/day      0.00   
32152  Protein supply quantity (g/capita/day)     g/capita/day      0.01   
32153      Fat supply quantity (g/capita/day)     g/capita/day      0.01   

          Y2015     Y2016     Y2017     Y2018  
30715  24234.00  24894.00  25571.00  26262.00  
30716      0.00      0.00      0.00      0.00  
30717   1922.00   1918.00   1943.00   1938.00  
30718     43.26     43.35     43.94     44.17  
30719     22.97     23.83     25.26     24.12  
...         ...       ...       ...       ...  
32149     11.00     11.00     11.00     12.00  
32150      0.44      0.44      0.44      0.44  
32151      0.00      0.00      0.00      0.00  
32152      0.01      0.01      0.01      0.01  
32153      0.01      0.01      0.01      0.01  

[1439 rows x 12 columns]

In [8]:
# total protein supply quantity in Madagascar in 2015
Madagascar_filter = food[food['Area']== 'Madagascar']
Madagascar_filter.groupby('Element')['Y2015'].sum()  

Element
Domestic supply quantity                  31214.98
Export Quantity                             494.75
Fat supply quantity (g/capita/day)           91.85
Feed                                       2070.22
Food                                      21120.65
Food supply (kcal/capita/day)              7685.00
Food supply quantity (kg/capita/yr)         871.59
Import Quantity                            1721.80
Losses                                     2176.00
Other uses (non-food)                      3957.12
Processing                                 1803.00
Production                                29482.89
Protein supply quantity (g/capita/day)      173.05
Residuals                                  -616.00
Seed                                        699.00
Stock Variation                            -505.00
Total Population - Both sexes             24234.00
Name: Y2015, dtype: float64

In [9]:
# year with the least correlation with 'Element code'
food.corr()

Area Code  Item Code  Element Code     Y2014     Y2015  \
Area Code      1.000000  -0.005159     -0.000209  0.006164  0.005472   
Item Code     -0.005159   1.000000     -0.024683  0.021722  0.020857   
Element Code  -0.000209  -0.024683      1.000000  0.024457  0.023889   
Y2014          0.006164   0.021722      0.024457  1.000000  0.994647   
Y2015          0.005472   0.020857      0.023889  0.994647  1.000000   
Y2016          0.005247   0.020109      0.023444  0.996081  0.995739   
Y2017          0.005006   0.021494      0.024254  0.995230  0.988048   
Y2018          0.005665   0.021314      0.024279  0.994872  0.988208   

                 Y2016     Y2017     Y2018  
Area Code     0.005247  0.005006  0.005665  
Item Code     0.020109  0.021494  0.021314  
Element Code  0.023444  0.024254  0.024279  
Y2014         0.996081  0.995230  0.994872  
Y2015         0.995739  0.988048  0.988208  
Y2016         1.000000  0.992785  0.992757  
Y2017         0.992785  1.000000  0.998103  
Y2018         0.992757  0.998103  1.000000

In [10]:
# to specify the column for the correlation check
food.corr()['Element Code']

Area Code      -0.000209
Item Code      -0.024683
Element Code    1.000000
Y2014           0.024457
Y2015           0.023889
Y2016           0.023444
Y2017           0.024254
Y2018           0.024279
Name: Element Code, dtype: float64

In [11]:
y = [(2,4), (7,8), (1,5,9)] # assign element 8 fom the list to a variable x
type(y)
y[1][1]

8

In [12]:
# total number of the sum of processing in 2017
food.groupby('Element')['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [13]:
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [14]:
# area with the highest sum in 2017
food.groupby('Area')['Y2017'].sum().sort_values(ascending = False)[:5]

Area
Nigeria         1483268.23
Egypt            866379.92
South Africa     517590.54
Ethiopia         448683.76
Morocco          388495.36
Name: Y2017, dtype: float64

In [15]:
# Total number of unique countries
len(food['Area'].unique())

49

In [16]:
# Total number & percentage of missing data in 2014 to 3 decimal places

missing = food.isnull().sum()
missing

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [17]:
y2014 = missing.loc['Y2014']
y2014

1589

In [18]:
tot_rows = food.shape[0]
tot_rows

60943

In [19]:
y2014/tot_rows*100

2.6073544131401474

In [20]:
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [21]:
df_list = [[35, 'Portugal', 94], 
           [33, 'Argentina', 93], 
           [30 , 'Brazil', 92]]

df1 = pd.DataFrame(df_list, columns = ['Age','Nationality','Overall'],
                   index = [1,2,3])
print(df1)

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92


In [22]:
food.groupby('Element')['Y2014', 'Y2015', 'Y2016','Y2017', 'Y2018'].sum()

C:\Users\QUEEN\AppData\Local\Temp\ipykernel_14136\1585514188.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  food.groupby('Element')['Y2014', 'Y2015', 'Y2016','Y2017', 'Y2018'].sum()


Y2014       Y2015       Y2016  \
Element                                                                      
Domestic supply quantity                1996716.35  2021493.55  2044842.70   
Export Quantity                          150020.64   157614.47   151920.46   
Fat supply quantity (g/capita/day)        10225.56    10235.74    10102.77   
Feed                                     216927.89   225050.22   228958.65   
Food                                    1212332.49  1232361.10  1247022.17   
Food supply (kcal/capita/day)            454257.00   453383.00   451810.00   
Food supply quantity (kg/capita/yr)       49650.63    49345.13    48985.28   
Import Quantity                          274144.48   267018.46   286582.78   
Losses                                   153223.00   155439.00   157787.00   
Other uses (non-food)                     78718.13    66254.41    69563.68   
Processing                               282923.00   287929.00   280631.00   
Production                              1931287.75  1947019.39  1943537.15   
Protein supply quantity (g/capita/day)    11836.46    11833.95    11779.69   
Residuals                                 30149.00    30045.00    37224.00   
Seed                                      21922.92    23976.82    23389.20   
Stock Variation                           58749.83    34910.99    33140.12   
Total Population - Both sexes           1031585.00  1058081.00  1085107.00   
Tourist consumption                         416.00      349.00       89.00   

                                             Y2017       Y2018  
Element                                                         
Domestic supply quantity                2088198.10  2161192.10  
Export Quantity                          182338.80   181594.80  
Fat supply quantity (g/capita/day)        10253.84    10258.69  
Feed                                     223705.68   233489.68  
Food                                    1258888.28  1303841.28  
Food supply (kcal/capita/day)            454681.00   455261.00  
Food supply quantity (kg/capita/yr)       48690.04    49056.85  
Import Quantity                          294559.09   287997.09  
Losses                                   160614.00   163902.00  
Other uses (non-food)                     91645.97    91300.97  
Processing                               292836.00   308429.00  
Production                              2030056.89  2075072.89  
Protein supply quantity (g/capita/day)    11842.45    11833.56  
Residuals                                 35500.00    34864.00  
Seed                                      24870.14    25263.14  
Stock Variation                           54316.91    20577.91  
Total Population - Both sexes           1112641.00  1140605.00  
Tourist consumption                          91.00       90.00

In [23]:
# To check for the number of rows and columns in a pandas DataFrame named df - df.shape\
food.shape

(60943, 12)

In [24]:
# Area with the 7th lowest sum in 2017
food.groupby('Area')['Y2017'].sum().sort_values(ascending = True)[:7]

Area
Sudan (former)               0.00
Ethiopia PDR                 0.00
Comoros                     59.84
Seychelles                 442.34
Sao Tome and Principe    12662.63
Cabo Verde               14650.74
Guinea-Bissau            19102.77
Name: Y2017, dtype: float64

Python inbuilt module - Pandas

In [25]:
# mean and standard deviation for 2017 
food.groupby(['Y2017']).mean()

Area Code  Item Code  Element Code     Y2014     Y2015     Y2016  \
Y2017                                                                         
-1582.0         59.0     2722.5        5072.0    2731.0      47.0    -985.0   
-1200.0        144.0     2532.0        5072.0       0.0       0.0     915.0   
-1159.0        144.0     2907.0        5072.0    -219.0      -3.0     915.0   
-865.0         215.0     2913.0        5072.0    2308.0    2505.0    -195.0   
-860.0         215.0     2556.0        5072.0     480.0     572.0    -212.0   
...              ...        ...           ...       ...       ...       ...   
 96443.0        59.0     2501.0         511.0   90425.0   92443.0   94447.0   
 106400.0      238.0     2501.0         511.0   98094.0  100835.0  103603.0   
 112625.0      159.0     2907.0        5301.0  108756.0  110798.0  116483.0   
 117702.0      159.0     2907.0        5511.0  109593.0  111663.0  119330.0   
 190873.0      159.0     2501.0         511.0  176405.0  181137.0  185960.0   

              Y2018  
Y2017                
-1582.0     -2156.0  
-1200.0     -1445.0  
-1159.0     -1442.0  
-865.0        -14.0  
-860.0        -61.0  
...             ...  
 96443.0    98424.0  
 106400.0  109224.0  
 112625.0  117038.0  
 117702.0  118172.0  
 190873.0  195875.0  

[4537 rows x 7 columns]

In [26]:
# mean and standard deviation for 2017 to 2 decimal places
food.describe()

Area Code     Item Code  Element Code          Y2014          Y2015  \
count  60943.000000  60943.000000  60943.000000   59354.000000   59395.000000   
mean     134.265576   2687.176706   3814.856456     134.196282     135.235966   
std       72.605709    146.055739   2212.007033    1567.663696    1603.403984   
min        4.000000   2501.000000    511.000000   -1796.000000   -3161.000000   
25%       74.000000   2562.000000    684.000000       0.000000       0.000000   
50%      136.000000   2630.000000   5142.000000       0.090000       0.080000   
75%      195.000000   2775.000000   5511.000000       8.340000       8.460000   
max      276.000000   2961.000000   5911.000000  176405.000000  181137.000000   

               Y2016          Y2017          Y2018  
count   59408.000000   59437.000000   59507.000000  
mean      136.555222     140.917765     143.758381  
std      1640.007194    1671.862359    1710.782658  
min     -3225.000000   -1582.000000   -3396.000000  
25%         0.000000       0.000000       0.000000  
50%         0.080000       0.100000       0.070000  
75%         8.430000       9.000000       9.000000  
max    185960.000000  190873.000000  195875.000000

In [27]:
food.head()

Area Code     Area  Item Code         Item  Element Code  \
0          4  Algeria       2501   Population           511   
1          4  Algeria       2501   Population          5301   
2          4  Algeria       2901  Grand Total           664   
3          4  Algeria       2901  Grand Total           674   
4          4  Algeria       2901  Grand Total           684   

                                  Element             Unit     Y2014  \
0           Total Population - Both sexes     1000 persons  38924.00   
1                Domestic supply quantity      1000 tonnes      0.00   
2           Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3  Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4      Fat supply quantity (g/capita/day)     g/capita/day     80.06   

      Y2015     Y2016     Y2017     Y2018  
0  39728.00  40551.00  41389.00  42228.00  
1      0.00      0.00      0.00      0.00  
2   3379.00   3372.00   3341.00   3322.00  
3     94.35     94.72     92.82     91.83  
4     79.36     77.40     80.19     77.28